'use strict';

const TEST_PACKAGE_NAME = 'Test Package 1';
const TEST_PACKAGE_RESTORATION_PRICE = '10.00';
const TEST_PACKAGE_REVENUE_SHARE = '5.00';

module.exports = {
  TEST_PACKAGE_NAME,
  TEST_PACKAGE_RESTORATION_PRICE,
  TEST_PACKAGE_REVENUE_SHARE,
};